name: Wochenspruch
description: Jeden Tag den aktuellen Wochenspruch

version: 1.0.2+4

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  test: ^1.5.1

flutter:
  uses-material-design: true


